Seminar4 assignment
IN-SOPT-ANDROID/yubeen-park pull request #3
Opened 2022-11-18 11:06 UTC by YuBeen-Park

- 회원가입/로그인 기능 구현하기
- Home 화면 꾸미기 -> GalleryFragment

2022-11-20 14:52 UTC, b1urrrr approved these changes
이번 주 과제하고 솝커톤까지 하느라 정말 고생 많았어요 🥲

2022-11-20 14:52 UTC, b1urrrr commented on app/src/main/java/org/sopt/sample/presentation/login/LoginActivity.kt
> +            fail_login_toast(it)
뷰모델 사용까지 굿굿!! 👍👍👍

2022-11-20 14:52 UTC, b1urrrr commented on app/src/main/java/org/sopt/sample/GalleryFragment.kt
> +        galleryAdapter.setItems(galleryList)
그리드 설정까지 굿굿 👍👍

2022-11-20 14:52 UTC, b1urrrr commented on app/src/main/java/org/sopt/sample/adapter/GalleryAdapter.kt
> +            Glide.with(binding.root).load(user.avatar).error(R.drawable.github)
오 저도 에러 이미지 넣어놔야겠어요!

2022-11-20 14:52 UTC, b1urrrr commented on app/src/main/java/org/sopt/sample/presentation/signup/SignUpActivity.kt
> +                    check_et_email.isNotEmpty() && check_et_name.isNotEmpty() && check_et_pw.isNotEmpty()
요 로직이 여러번 사용되는 것 같아서 함수로 따로 빼주면 좋을 것 같아요!

2022-11-21 06:42 UTC, KWY0218 requested changes
과제하시느라 수고하셨습니다 ~ !
뷰모델 통한 통신 너무 좋네요 ~ ^_^

2022-11-21 06:42 UTC, KWY0218 commented on app/src/main/java/org/sopt/sample/GalleryFragment.kt
> +    }
이전에 문서에서 봤었는데, 어디서 봤는지 까먹어서 문서 url을 못 올리지만..
companion object는 보통 코드 최하단에 적는 것이 컨벤션입니다 !

2022-11-21 06:42 UTC, KWY0218 commented on app/src/main/java/org/sopt/sample/GalleryFragment.kt
> +                        galleryAdapter.setItems(galleryList)
```suggestion
                        galleryAdapter.setItems(it.data.toList())
```
1. 우선 해당 로직에서 clear 이후 add만 하기 때문에 `galleryList`를 private var 로 설정할 이유가 없어 보입니다.
2. collection 내장 함수인 `toList` 를 사용하면 위 로직을 한줄로 줄일 수 있습니다.
    `toList` 내장 함수는 새 주소의 리스트를 반환하는 함수입니다.
3. 서버통신을 통해서 데이터를 받아서 항상 다른 주소의 리스트가 들어오기 때문에 `it.data.toList()` 를 안하고 `it.data` 만 넣어도 될 것 같다는 생각이 듭니다..!

2022-11-21 06:42 UTC, KWY0218 commented on app/src/main/java/org/sopt/sample/adapter/GalleryAdapter.kt
> +    private var user_items: List<ResponseUserList.userListInfo>? = null
코틀린 컨벤션은 스네이크 케이스가 아닌 카멜 케이스 입니다!

또, null이 아닌 emptyList로 초기화 하면, fragment에서 adapter를 만들 때 setItems 호출을 안해도 되니 emptyList도 괜찮을 것 같습니다!!

2022-11-21 06:42 UTC, KWY0218 commented on app/src/main/java/org/sopt/sample/data/remote/ApiFactory.kt
> +            .baseUrl("http://3.39.169.52:3000/")
보안을 위해 local properties 안에 base url 을 숨기는 방법을 알아보는 것을 추천 드립니다 !

2022-11-21 06:42 UTC, KWY0218 commented on app/src/main/java/org/sopt/sample/presentation/login/LoginActivity.kt
> +    private fun fail_login_toast(errorMessage: String) {
카멜 케이스 ! ! !

2022-11-21 06:42 UTC, KWY0218 commented on app/src/main/java/org/sopt/sample/presentation/signup/SignUpActivity.kt
> +    private var check_et_name: String = ""
카멜 케이스 !

2022-11-21 06:42 UTC, KWY0218 commented on app/src/main/java/org/sopt/sample/presentation/login/LoginActivity.kt
> +            }
1. it.status in 200 until 300 (200<= i<300)
    이런 식으로도 표현할 수 있습니다 !

아래 리뷰에서 계속...

2022-11-21 06:42 UTC, KWY0218 commented on app/src/main/java/org/sopt/sample/presentation/login/LoginViewModel.kt
> +            }
2. `response.isSuccessful` 안에 있는 코드들은 status code가 `200~300` 인 상태를 보장합니다.
    그래서 activity에서 status 로 구분하는 것 보다, 
    viewmodel에선 true, false 값을 변경하고, 
    activty의 observe는 해당 boolean 값을 관찰하는 것이 더 좋을 것 같습니다.

2022-11-21 06:42 UTC, KWY0218 commented on app/src/main/java/org/sopt/sample/presentation/login/LoginViewModel.kt
> +            }
해당 에러 메시지는 토스트에 띄울 것이므로, 뭔가 뷰 작업에 가깝다고 생각이 듭니다.
그래서 저는 viewmodel 보다 activity에 있는 것이 더 자연스러워 보인다고 생각합니다 !

2022-11-21 06:42 UTC, KWY0218 commented on app/src/main/java/org/sopt/sample/presentation/signup/SignUpViewModel.kt
> +            }
제가 위에서 viewmodel에서 통신 성공, 실패 일 때 boolean 값을 설정하고, activity에선 해당 boolean 값을 관찰해달라고 했지만 문제가 있습니다

if(response.isSuccessful) <--- 200 ~ 300
else  <-  300 ~ 500
onFailure <- 500 ~

이렇게 3개의 경우가 나오지만, boolean 값으론 2개 밖에 처리하지 못합니다.

enum class 또는 sealed class 를 이용해서 위 3개의 분기 처리 한번 해보는 것을 추천 드립니다...!

2022-11-21 10:34 UTC, KWY0218 commented on app/build.gradle
> +    annotationProcessor 'com.github.bumptech.glide:compiler:4.12.0'
annotationProcessor 의 경우 자바의 어노테이션 프로세싱 툴입니다.
코틀린의 어노테이션 프로세싱 툴인 kapt를 쓰는 게 좋을 것 같습니다.

2022-11-22 04:59 UTC, YuBeen-Park commented on app/src/main/java/org/sopt/sample/presentation/signup/SignUpActivity.kt
> +                    check_et_email.isNotEmpty() && check_et_name.isNotEmpty() && check_et_pw.isNotEmpty()
수정하겠습니당~~

2022-11-22 05:00 UTC, YuBeen-Park commented on app/src/main/java/org/sopt/sample/GalleryFragment.kt
> +    }
그렇군요! 수정하겠습니다~

2022-11-22 05:04 UTC, YuBeen-Park commented on app/src/main/java/org/sopt/sample/GalleryFragment.kt
> +                        galleryAdapter.setItems(galleryList)
어차피 들어올때마다 바뀌니까 galleryList가 필요없는 거였군용 galleryList 변수 삭제하고 로직 수정하겠습니당~~

2022-11-22 15:28 UTC, waterminn approved these changes
으아... 솝커톤에 정신이 팔려서 코드리뷰 잊고 있었네요😥 뒤늦게라도 남기고 갑니당 과제하느라 수고하셨어요~!!

2022-11-22 15:28 UTC, waterminn commented on app/src/main/java/org/sopt/sample/data/UserInfo.kt
> +)
전 `@SerialName`을 모든 곳에 썼었는데 이렇게 서버에서 사용하는 이름이랑 다르게 쓸 때만 저걸 쓰는게 훨씬 낫겠네요!

2022-11-22 15:28 UTC, waterminn commented on app/src/main/java/org/sopt/sample/GalleryFragment.kt
> +        galleryAdapter.setItems(galleryList)
오오... 이렇게 리사이클러뷰를 그리드로 설정하는거군요...! 이제야 이해가 가네요 배워갑니당!

2022-11-30 06:10 UTC, KWY0218 commented on app/src/main/java/org/sopt/sample/data/remote/ResponseUserList.kt
> +data class ResponseUserList(
```suggestion
data class ResponseUser(
```
해당 data class가 List에 담기기 직전이기 때문에 `ResponseUserList` 라는 이름은 다소 어색하단 느낌이 듭니다..!
`ReponseUser` 가 더 좋을 것 같습니다..!

2022-12-02 05:42 UTC, YuBeen-Park commented on app/src/main/java/org/sopt/sample/presentation/login/LoginActivity.kt
> +                is AuthNetworkState.Error -> failLoginSnackbar(getString(R.string.network_error))
요런 느낌으로 하는거 맞을까요옹??
@KWY0218

2022-12-02 05:42 UTC, YuBeen-Park commented on app/src/main/java/org/sopt/sample/presentation/signup/SignUpViewModel.kt
> +            }
수정했는데 한번 봐주세영

2022-12-02 05:49 UTC, KWY0218 commented on app/src/main/java/org/sopt/sample/presentation/login/LoginActivity.kt
> +                is AuthNetworkState.Error -> failLoginSnackbar(getString(R.string.network_error))
넹넹!!!!
Success, Failure 앞에도 `is` 붙여주고,
또, Success 안에 startActivity 로직만 있어도 충분할 거 같습니다

2022-12-02 06:09 UTC, YuBeen-Park commented on app/src/main/java/org/sopt/sample/presentation/login/LoginActivity.kt
> +                is AuthNetworkState.Error -> failLoginSnackbar(getString(R.string.network_error))
휴~ 수정했습니당~~

2022-12-02 06:21 UTC, KWY0218 approved these changes
수고하셨습니당 ~ 👍

2022-12-02 07:33 UTC, merged