Seminar6 assignment
IN-SOPT-ANDROID/yubeen-park pull request #4
Opened 2022-12-02 14:35 UTC by YuBeen-Park

1. 필수과제
- [ ]  홈 화면 UI Layer (ViewModel 적용)

- [ ] 회원가입 화면에서 경고 적용

2.심화과제
- [ ] 회원가입 화면에 양방향 데이터 바인딩 적용해보기

2022-12-03 07:34 UTC, KWY0218 requested changes
작업하시느라 고생하셨습니다 ! ! 👍

2022-12-03 07:34 UTC, KWY0218 commented on app/src/main/java/org/sopt/sample/presentation/home/HomeFragment.kt
> +                is NetworkState.Failure -> failUserSnackbar("예상치 못한 오류가 발생했습니다.")
ㅋㅋㅋㅋ귀찮음 검거
문자열 한번 클릭하고 `alt + enter` 누르면 string 리소스 편하게 추가할 수 있습니다 ~

2022-12-03 07:34 UTC, KWY0218 commented on app/src/main/java/org/sopt/sample/presentation/home/HomeFragment.kt
> +    private lateinit var gridManager: GridLayoutManager
gridManager는 처음 한번만 사용하고 그 뒤로 사용 하지 않는 것 같습니다.
전역 변수로 선언한 이유가 있을까요?

2022-12-03 07:34 UTC, KWY0218 commented on app/src/main/java/org/sopt/sample/presentation/home/HomeViewModel.kt
> +                    _userResult.value = NetworkState.Success
해당 코드도 좋습니다!! 좋은데~~
HomeActivity에서 `userList` 를 observe 하면, Success 로 알려줄 필요 없이 `userList` 값이 바뀌면 알아서 바뀌기 때문에
코드 중복 아닌가~ 하는 생각이 살짝 듭니다...!

2022-12-03 07:34 UTC, KWY0218 commented on app/src/main/java/org/sopt/sample/presentation/home/HomeFragment.kt
> +    private fun initUserInfo() {
해당 함수는 `userList`를 관찰할 뿐만 아니라, error 코드도 같이 관찰하고 있습니다.
`initUserInfo` 함수 명 보다는 `observeOnEvent` 와 같은 함수 명이 좀 더 좋을 것 같습니다..!

2022-12-03 13:10 UTC, b1urrrr approved these changes
과제하시느라 고생하셨습니다 👏👏

2022-12-03 13:10 UTC, b1urrrr commented on app/src/main/java/org/sopt/sample/data/remote/NetworkState.kt
> +}
sealed 클래스는 이런 식으로 만드는군요!!
잘 배워가요 🤭

2022-12-03 13:10 UTC, b1urrrr commented on app/src/main/java/org/sopt/sample/presentation/home/HomeFragment.kt
> +    }
저번 세미나에서 다룬 확장함수로 만들어봐도 좋을 것 같아요!

2022-12-03 13:10 UTC, b1urrrr commented on app/src/main/java/org/sopt/sample/presentation/signup/SignUpViewModel.kt
> +    }
```suggestion
    private fun emailRegex(email: String): Boolean {
        return email.matches("^(?=.*[a-zA-Z])(?=.*[0-9]).{6,10}$".toRegex())
    }

    private fun passwordRegex(password: String): Boolean {
        return password.matches("^(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[$&+?@#<>^*%!]).{6,12}$".toRegex())
    }
```
`.`을 쓰면 좀 더 간단하게 정규식을 표현할 수 있는 것 같아요!
대문자도 영문 조건에 포함해주는 건 어떤가요?

2022-12-03 13:10 UTC, b1urrrr commented on app/src/main/res/layout/activity_sign_up.xml
> +    </data>
양방향 데이터바인딩까지 굿굿!! 👍👍

2022-12-03 13:10 UTC, b1urrrr commented on app/src/main/res/layout/activity_sign_up.xml
> +            android:visibility="@{viewModel.emailFlag ? View.GONE : View.VISIBLE, default=gone}"
오오 디폴트 값도 넣어줄 수 있군요!

2022-12-03 13:40 UTC, KWY0218 commented on app/src/main/java/org/sopt/sample/data/remote/NetworkState.kt
> +}
```suggestion
sealed class NetworkState {
    object Success : NetworkState()
    object Failure : NetworkState()
    data class Error(val e: Throwable) : NetworkState()
}
```
해당 error 클래스는 Throwable을 담기 위해 만든 class 이고, 
data class는 `toString`, `equals` , `copy`, `hashcode`를 자동으로 만들어주기 때문에
class 보다 data class로 만드는 것이 더 좋을 것 같습니다.

2022-12-03 14:04 UTC, KWY0218 commented on app/src/main/java/org/sopt/sample/presentation/home/HomeViewModel.kt
> +                    _userResult.value = NetworkState.Success
셤 공부하기 싫어서 깃허브 뒤적거리다가 발견 했는데
[수진님 코드](https://github.com/IN-SOPT-ANDROID/sujin-lim/pull/4/files#diff-0b97d552ba6a4095f75afa091fe8176365068122443fb1d1035df2cf5e1fb430) UiState 처럼 만들면, `userList` 변수도 없앨 수 있고 제가 앞서 리뷰 달았던 문제도 해결할 수 있을 것 같습니다

2022-12-05 05:17 UTC, waterminn approved these changes
6주차 과제도 수고하셨습니다~!! 서버통신 좀 감잡고 가요👍

2022-12-05 05:17 UTC, waterminn commented on app/src/main/java/org/sopt/sample/presentation/signup/SignUpActivity.kt
> +        binding = DataBindingUtil.setContentView(this, R.layout.activity_sign_up)
앗 이걸 추가하는걸 까먹었네요😅 지난주에 설명해줘서 고마웠어요~!!

2022-12-05 05:17 UTC, waterminn commented on app/src/main/res/layout/activity_sign_up.xml
> +            android:visibility="@{viewModel.emailFlag ? View.GONE : View.VISIBLE, default=gone}"
오 디폴트는 저도 처음 알았네요...! 경고문구 버그 수정할 때 한번 활용해보겠습니다👍

2022-12-05 05:17 UTC, waterminn commented on app/src/main/res/layout/activity_sign_up.xml
> +            tools:layout_editor_absoluteX="40dp" />
저도 코드리뷰 반영하면서 바꾸려고 하는데 edittext 아래쪽에 textview로 경고문구를 표시하는 것보다 `TextInputLayout` 이걸 사용하는게 구현하기 더 편할 것 같더라고요...!

[공식문서](https://developer.android.com/reference/com/google/android/material/textfield/TextInputLayout) 놓고 갑니당

2022-12-13 08:00 UTC, YuBeen-Park commented on app/src/main/java/org/sopt/sample/presentation/home/HomeFragment.kt
> +                is NetworkState.Failure -> failUserSnackbar("예상치 못한 오류가 발생했습니다.")
딱 걸렸다,, ㅎ
아주 예리한걸?

2022-12-13 08:02 UTC, YuBeen-Park commented on app/src/main/java/org/sopt/sample/presentation/home/HomeFragment.kt
> +    private lateinit var gridManager: GridLayoutManager
언젠간 사용할 것 같았나봐요 ㅎ 지역변수로 바꿔도 될것 같네요
(아주 예리한걸?)

2022-12-14 19:59 UTC, KWY0218 commented on app/src/main/java/org/sopt/sample/data/state/UiState.kt
> +package org.sopt.sample.data.state
data 패키지는 data 관련 비즈니스 로직만 있는 곳인데 `UiState` 가 있는 것이 다소 부자연스럽다고 생각이 듭니다..! 차라리 util 패키지에 넣는 것이 자연스럽다고 생각이 듭니다!

2022-12-14 19:59 UTC, KWY0218 commented on app/src/main/java/org/sopt/sample/presentation/home/HomeFragment.kt
> +                    //TODO 8주차 과제
UiState를 사용하면 else 사용을 안 해도 됩니다..! 가독성을 위해 else 사용을 지양해주세요..!

2022-12-14 19:59 UTC, KWY0218 commented on app/src/main/java/org/sopt/sample/presentation/home/HomeFragment.kt
> +        var gridManager = GridLayoutManager(requireContext(), SPAN_COUNT)
`val` 를 사용해도 충분하다고 생각이 듭니다..!

2022-12-14 19:59 UTC, KWY0218 commented on app/src/main/java/org/sopt/sample/presentation/home/HomeViewModel.kt
> +                _userResult.value = UiState.Loading(false)
Loading 과 Empty일 때 boolean 값을 넣는 이유가 있을까요??
별다른 이유가 없다면 data class가 아닌 object로 변경하면 좋을 것 같습니다.

2022-12-15 05:13 UTC, YuBeen-Park commented on app/src/main/res/layout/activity_sign_up.xml
> +            tools:layout_editor_absoluteX="40dp" />
변경해보았어용~~ 경고문구 표시하는데 훨씬 편한거같아요!!
속성 중에 error 관련된 속성들에는 data binding 지원을 안하는듯해용!(이것때매 시간 많이 잡아먹은,,, ㅠ)

2022-12-15 05:15 UTC, YuBeen-Park commented on app/src/main/res/layout/activity_sign_up.xml
> +            tools:layout_editor_absoluteX="40dp" />
글구 혹시 커스텀하게 된다면 저 좀 알려주세요 ㅠ
커스텀하다가 화딱지나서 그냥 기본 제공하는 거로 일단 구현했습니당

2022-12-15 05:18 UTC, YuBeen-Park commented on app/src/main/java/org/sopt/sample/presentation/home/HomeFragment.kt
> +                    //TODO 8주차 과제
저거 when구문으로 하면 UiState에 있는거 다 써야되가지구 그런건데 else쓰면 확실히 가독성이 떨어지는거 같아여
만약에 UiState 중에 여기서 로직 구현할 게 없으면 그냥 비어있는 채로 두는게 더 나은가요?? 
(is UiState.Success -> {} 요런느낌)

2022-12-15 05:19 UTC, YuBeen-Park commented on app/src/main/java/org/sopt/sample/presentation/home/HomeViewModel.kt
> +                _userResult.value = UiState.Loading(false)
Loading은 로딩중인지 아닌지 boolean값으로 구분하려고 그런건데 empty는 굳이 그럴필요 없느너 같네용
수정하겠습니다!

2022-12-15 05:56 UTC, KWY0218 commented on app/src/main/java/org/sopt/sample/presentation/home/HomeFragment.kt
> +                    //TODO 8주차 과제
넹넹~! `is UiState.Success -> Unit` 도 괜찮을 거 같습니다~!

2022-12-15 06:06 UTC, KWY0218 commented on app/src/main/java/org/sopt/sample/presentation/home/HomeFragment.kt
> +                UiState.Init -> TODO()
> Loading은 로딩중인지 아닌지 boolean값으로 구분하려고 그런건데

라고 했지만, Loading 에서 boolean 값을 이용하는 모습이 없습니다..! 그래서 저는 objesct 로 충분할 것 같다는 생각이 듭니다.

또, `Init` 의 필요성이 안 느껴집니다. 
초기 값을 위해 만든 것이라고 생각이 드는데, 초기 값을 `Empty`로 만들어도 괜찮다고 생각이 듭니다!

2022-12-15 06:06 UTC, KWY0218 commented on app/src/main/java/org/sopt/sample/presentation/home/HomeViewModel.kt
> +    }
로딩뷰는 보통 서버 통신 중일 때 작동을 하지만 
init 에 Loading 넣게 되면 서버 통신을 아직 안 했지만 
로딩이 돌아가는 것이 부자연스럽다는 느낌이 듭니다..!

2022-12-15 06:06 UTC, KWY0218 commented on app/src/main/java/org/sopt/sample/presentation/home/HomeViewModel.kt
> +                _userResult.value = UiState.Loading(false)
```suggestion
    fun getUser() {
        _userResult.value = UiState.Loading()
        userService.getUserList().enqueue(object : Callback<ResponseUser> {
            override fun onResponse(
                call: Call<ResponseUser>,
                response: Response<ResponseUser>
            ) {
```
로딩을 위로 올려서, 요런 식으로 하면 좋을 것 같다고 생각이 듭니다..!

2022-12-15 08:02 UTC, YuBeen-Park commented on app/src/main/java/org/sopt/sample/presentation/home/HomeFragment.kt
> +                UiState.Init -> TODO()
아 그렇네여? 한번 수정해볼게엽

2022-12-26 00:16 UTC, KWY0218 approved these changes
7주차 과제는 없지만... !😭 
그동안 과제 하느라 수고했습니다~~!!! 👍 👍

2022-12-26 00:16 UTC, KWY0218 commented on app/src/main/java/org/sopt/sample/presentation/home/LoadingDialog.kt
> +}
다른 로딩이 필요한 뷰가 생길 때에도 쉽게 사용할 수 있겠군요 👍 👍

2022-12-26 06:08 UTC, merged